const textureNames = [
  'concrete_brick1.jpg',
  'concrete_brick2.jpg',
  'concrete_tile1.jpg',
  'concrete_tile2.jpg',
  'concrete_tile3.jpg',
  'concrete1.jpg',
  'concrete2.jpg',
  'floor_carpet1.jpg',
  'floor_grass1.jpg',
  'floor1.jpg',
  'fresco1.jpg',
  'hedge1.jpg',
  'hedge2.jpg',
  'light_brick1.jpg',
  'marble1.jpg',
  'plaster1.jpg',
  'red_brick1.jpg',
  'rusted_steel1.jpg',
  'stone2.jpg',
  'stripes_creamsicle1.jpg',
]

const PATH = process.env.PUBLIC_URL + '/textures/';

const WALL = { type: 'wall', textureType: 'image', textureConfig: { name: 'red_brick1' }, faces: { north: null, east: null, south: null, west: null } };
const EXT_WALL = { type: 'wall', textureType: 'image', textureConfig: { name: 'hedge1' }, faces: { north: null, east: null, south: null, west: null } };
const FLOOR = { type: 'floor', textureType: 'image', textureConfig: { name: 'floor_grass1' }, };
const INT_FLOOR = { type: 'floor', textureType: 'image', textureConfig: { name: 'concrete_brick2' }, ceilingConfig: { textureType: 'image', textureConfig: { name: 'fresco1'}}};

export default {
  textures: textureNames.map(name => PATH + name),
  sprites: [],
  tiles: [],
  map: {
    grid: [
      [EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,WALL,INT_FLOOR,WALL,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,INT_FLOOR,INT_FLOOR,INT_FLOOR,WALL,WALL,WALL,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,INT_FLOOR,INT_FLOOR,INT_FLOOR,INT_FLOOR,INT_FLOOR,INT_FLOOR,INT_FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,INT_FLOOR,INT_FLOOR,INT_FLOOR,WALL,WALL,WALL,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,WALL,INT_FLOOR,WALL,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,EXT_WALL],
      [EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL,EXT_WALL],    
    ],
    playerPos: {
      x: 9.5,
      y: 20
    },
    playerDir: {
      x: 0,
      y: -1
    },
    playerPlane: {
      x: -0.66,
      Y: 0
    },
    skyGradient: [
      {
        stop: 0,
        color: "#7AA1D2"
      },
      {
        stop: .8,
        color: "#DBD4B4"
      },
      {
        stop: 1,
        color: "#CC95C0"
      }
    ],
  },
}